"""baseline schema

Revision ID: 8f95773ab0c6
Revises: 
Create Date: 2026-08-26 18:25:05.917239

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f95773ab0c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_status'), ['status'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=128), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_threat_type'), ['threat_type'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=96), nullable=False),
    sa.Column('original_instruction', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('triggered_rule_name', sa.String(length=128), nullable=False),
    sa.Column('intercept_reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('console_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('console_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_console_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_console_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_console_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_console_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_console_users_role'), ['role'], unique=False)

    op.create_table('intercept_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=96), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intercept_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intercept_logs_action_taken'), ['action_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_intercept_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intercept_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intercept_logs_threat_type'), ['threat_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_intercept_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('managed_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_api_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_key_prefix'), ['key_prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_last_used_at'), ['last_used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_api_keys_role'), ['role'], unique=False)

    op.create_table('replay_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_request_id', sa.String(length=96), nullable=False),
    sa.Column('replay_request_id', sa.String(length=96), nullable=False),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_runs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_runs_replay_request_id'), ['replay_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_replay_runs_source_request_id'), ['source_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_runs_verdict'), ['verdict'], unique=False)

    op.create_table('security_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('blacklist_keyword', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('system_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_policies_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_policies_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_security_policies_system_managed'), ['system_managed'], unique=False)

    op.create_table('tool_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('requires_admin_approval', sa.Boolean(), nullable=False),
    sa.Column('system_managed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_policies_allowed'), ['allowed'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_policies_system_managed'), ['system_managed'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_policies_tool_name'), ['tool_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_policies_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_policies_system_managed'))
        batch_op.drop_index(batch_op.f('ix_tool_policies_id'))
        batch_op.drop_index(batch_op.f('ix_tool_policies_allowed'))

    op.drop_table('tool_policies')
    with op.batch_alter_table('security_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_policies_system_managed'))
        batch_op.drop_index(batch_op.f('ix_security_policies_name'))
        batch_op.drop_index(batch_op.f('ix_security_policies_id'))
        batch_op.drop_index(batch_op.f('ix_security_policies_enabled'))

    op.drop_table('security_policies')
    with op.batch_alter_table('replay_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replay_runs_verdict'))
        batch_op.drop_index(batch_op.f('ix_replay_runs_source_request_id'))
        batch_op.drop_index(batch_op.f('ix_replay_runs_replay_request_id'))
        batch_op.drop_index(batch_op.f('ix_replay_runs_id'))
        batch_op.drop_index(batch_op.f('ix_replay_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_replay_runs_category'))

    op.drop_table('replay_runs')
    with op.batch_alter_table('managed_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_role'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_name'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_last_used_at'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_is_active'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_id'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_expires_at'))
        batch_op.drop_index(batch_op.f('ix_managed_api_keys_created_at'))

    op.drop_table('managed_api_keys')
    with op.batch_alter_table('intercept_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intercept_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_intercept_logs_threat_type'))
        batch_op.drop_index(batch_op.f('ix_intercept_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_intercept_logs_id'))
        batch_op.drop_index(batch_op.f('ix_intercept_logs_action_taken'))

    op.drop_table('intercept_logs')
    with op.batch_alter_table('console_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_console_users_role'))
        batch_op.drop_index(batch_op.f('ix_console_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_console_users_id'))
        batch_op.drop_index(batch_op.f('ix_console_users_email'))
        batch_op.drop_index(batch_op.f('ix_console_users_created_at'))

    op.drop_table('console_users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_risk_level'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_threat_type'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_request_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_created_at'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_status'))
        batch_op.drop_index(batch_op.f('ix_alert_events_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_created_at'))

    op.drop_table('alert_events')
    # ### end Alembic commands ###
